name: 'simple gitaction'

on: [push]

jobs:
  build:
    name: simpleGitactionJob
    runs-on: ubuntu-latest
    steps:
 
      - name: Gradle 권한설정
        run: chmod +x gradlew
      - name: Gradle Build
        run: ./gradlew build
